# Generated by Django 4.1.1 on 2024-09-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='image',
        ),
    ]
