# Generated by Django 4.1.1 on 2024-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_remove_profileimage_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/profile_pictures/old')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='old_pictures',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='social.oldpicture'),
        ),
    ]
