# Generated by Django 4.1.1 on 2024-09-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_oldpicture_userprofile_old_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='old_pictures',
        ),
        migrations.DeleteModel(
            name='OldPicture',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
