# Generated by Django 4.1.1 on 2024-09-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_alter_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
