# Generated by Django 4.1.1 on 2024-09-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
